replicaCount: 2
image:
  repository: hashicorp/http-echo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 5678

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}